#21 Add an ability to delete category
somoye/LunchDelivery pull request #31
Opened 2017-08-10 16:08 UTC by somoye

2017-08-10 16:27 UTC, chapluck commented on Client/js/admin_categories.js
> +            $(".delete-category").click(function() {
Here you subscribe on click of all ".delete-category" anchors, but you need to add handler to added anchor only.

2017-08-10 16:28 UTC, chapluck requested changes
Handle the comment

2017-09-13 17:30 UTC, somoye commented
@chapluck please check it again

2017-09-14 11:07 UTC, chapluck approved these changes

2017-09-14 11:07 UTC, merged