Ld30
somoye/LunchDelivery pull request #35
Opened 2017-10-25 19:58 UTC by paperplane90

2017-10-26 18:33 UTC, chapluck requested changes

2017-10-26 18:33 UTC, chapluck commented on Server/app.js
> +/*app.use(function (req, res, next) {
Remove comment symbols /*

2017-10-26 18:33 UTC, chapluck commented on Server/models/user.model.js
> +
remove redundant empty line

2017-10-26 18:33 UTC, chapluck commented on Server/routes/users.route.js
> +module.exports = router;
move exports assignment to the end of the file

2017-10-26 18:33 UTC, chapluck commented on Server/services/user.provider.js
> +			Promise.reject(new errors.BadRequest("Validation error (Please check you input)"))
add UniqueConstraintError handling

2017-10-31 19:38 UTC, paperplane90 commented
It is done

2017-10-31 19:45 UTC, chapluck approved these changes

2017-10-31 19:46 UTC, merged